#!/bin/bash

[[ -z $(grep BCM2711 /proc/cpuinfo) ]] && echo "You are not on a RPi!" && exit 1

echo "Installing configuration files..."

DIR=$(git rev-parse --show-toplevel)/rpi-config

if [[ -e ~/.bash_profile || -h ~/.bash_profile ]]; then
    rm -f ~/.bash_profile
fi
ln -s $DIR/.bash_profile ~/.bash_profile

if [[ -e ~/.xinitrc || -h ~/.xinitrc ]]; then
    rm -f ~/.xinitrc
fi
ln -s $DIR/.xinitrc ~/.xinitrc

echo "Done!"
