name: Update README.md

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Update readme
        run: python ./.github/actions/update_readme.py
